//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBS_Europe.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBS_Europe.App.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ABT_NoMembers {
            get {
                return ResourceManager.GetString("ABT-NoMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AH_Commitments {
            get {
                return ResourceManager.GetString("AH-Commitments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AH_Title {
            get {
                return ResourceManager.GetString("AH-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AS_Text {
            get {
                return ResourceManager.GetString("AS-Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AS_Title {
            get {
                return ResourceManager.GetString("AS-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_EG {
            get {
                return ResourceManager.GetString("AT-EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_ER {
            get {
                return ResourceManager.GetString("AT-ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_FN20 {
            get {
                return ResourceManager.GetString("AT-FN20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_FNR {
            get {
                return ResourceManager.GetString("AT-FNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_Format {
            get {
                return ResourceManager.GetString("AT-Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_Image {
            get {
                return ResourceManager.GetString("AT-Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_IR {
            get {
                return ResourceManager.GetString("AT-IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_N20 {
            get {
                return ResourceManager.GetString("AT-N20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_Nu20 {
            get {
                return ResourceManager.GetString("AT-Nu20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_NuG {
            get {
                return ResourceManager.GetString("AT-NuG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_PersonExist {
            get {
                return ResourceManager.GetString("AT-PersonExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_R20 {
            get {
                return ResourceManager.GetString("AT-R20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_RR {
            get {
                return ResourceManager.GetString("AT-RR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_Size {
            get {
                return ResourceManager.GetString("AT-Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_Title {
            get {
                return ResourceManager.GetString("AT-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_CR {
            get {
                return ResourceManager.GetString("B-CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_Exist {
            get {
                return ResourceManager.GetString("B-Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_FFormat {
            get {
                return ResourceManager.GetString("B-FFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_FMAX {
            get {
                return ResourceManager.GetString("B-FMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_FR {
            get {
                return ResourceManager.GetString("B-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_General {
            get {
                return ResourceManager.GetString("B_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_Individuals {
            get {
                return ResourceManager.GetString("B-Individuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_Looking {
            get {
                return ResourceManager.GetString("B-Looking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_MainD {
            get {
                return ResourceManager.GetString("B-MainD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_N50 {
            get {
                return ResourceManager.GetString("B-N50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_NR {
            get {
                return ResourceManager.GetString("B-NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_OtherD {
            get {
                return ResourceManager.GetString("B-OtherD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_Professionals {
            get {
                return ResourceManager.GetString("B-Professionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string B_Title {
            get {
                return ResourceManager.GetString("B-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_Contact {
            get {
                return ResourceManager.GetString("C-Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_Login {
            get {
                return ResourceManager.GetString("C-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_Password {
            get {
                return ResourceManager.GetString("C-Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_PasswordP {
            get {
                return ResourceManager.GetString("C-PasswordP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_RequiredPassword {
            get {
                return ResourceManager.GetString("C-RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_RequiredUsername {
            get {
                return ResourceManager.GetString("C-RequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_Title {
            get {
                return ResourceManager.GetString("C-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_User {
            get {
                return ResourceManager.GetString("C-User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_UserP {
            get {
                return ResourceManager.GetString("C-UserP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string C_WrongLogin {
            get {
                return ResourceManager.GetString("C-WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Cat_Title {
            get {
                return ResourceManager.GetString("Cat-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Add {
            get {
                return ResourceManager.GetString("Co-Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_AddE {
            get {
                return ResourceManager.GetString("Co-AddE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Choose {
            get {
                return ResourceManager.GetString("Co-Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_CR {
            get {
                return ResourceManager.GetString("Co-CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_D25 {
            get {
                return ResourceManager.GetString("Co-D25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_D250 {
            get {
                return ResourceManager.GetString("Co-D250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_DR {
            get {
                return ResourceManager.GetString("Co-DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Email {
            get {
                return ResourceManager.GetString("Co-Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_ENG {
            get {
                return ResourceManager.GetString("Co-ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_ER {
            get {
                return ResourceManager.GetString("Co-ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Error {
            get {
                return ResourceManager.GetString("Co-Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_File {
            get {
                return ResourceManager.GetString("Co-File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Firstname {
            get {
                return ResourceManager.GetString("Co-Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Lastname {
            get {
                return ResourceManager.GetString("Co-Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_ME50 {
            get {
                return ResourceManager.GetString("Co-ME50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MENG {
            get {
                return ResourceManager.GetString("Co-MENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Message {
            get {
                return ResourceManager.GetString("Co-Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MF50 {
            get {
                return ResourceManager.GetString("Co-MF50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MFR {
            get {
                return ResourceManager.GetString("Co-MFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MLN {
            get {
                return ResourceManager.GetString("Co-MLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MM20 {
            get {
                return ResourceManager.GetString("Co-MM20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MMR {
            get {
                return ResourceManager.GetString("Co-MMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Modify {
            get {
                return ResourceManager.GetString("Co-Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_ModifyE {
            get {
                return ResourceManager.GetString("Co-ModifyE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MP15 {
            get {
                return ResourceManager.GetString("Co-MP15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MPNG {
            get {
                return ResourceManager.GetString("Co-MPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_MS {
            get {
                return ResourceManager.GetString("Co-MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_N25 {
            get {
                return ResourceManager.GetString("Co-N25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_NR {
            get {
                return ResourceManager.GetString("Co-NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Number {
            get {
                return ResourceManager.GetString("Co-Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_PORE {
            get {
                return ResourceManager.GetString("Co-PORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Send {
            get {
                return ResourceManager.GetString("Co-Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_Subject {
            get {
                return ResourceManager.GetString("Co-Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_SuccessM {
            get {
                return ResourceManager.GetString("Co-SuccessM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_T25 {
            get {
                return ResourceManager.GetString("Co-T25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Co_TR {
            get {
                return ResourceManager.GetString("Co-TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string I_Learn {
            get {
                return ResourceManager.GetString("I-Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string I_Title {
            get {
                return ResourceManager.GetString("I-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string I_Trusted {
            get {
                return ResourceManager.GetString("I-Trusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string I_Welcome {
            get {
                return ResourceManager.GetString("I-Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string I_WhyIBS {
            get {
                return ResourceManager.GetString("I-WhyIBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string I_WhyText {
            get {
                return ResourceManager.GetString("I-WhyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_About {
            get {
                return ResourceManager.GetString("L-About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_Author {
            get {
                return ResourceManager.GetString("L-Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_Broker {
            get {
                return ResourceManager.GetString("L-Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_CompanyImage {
            get {
                return ResourceManager.GetString("L-CompanyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_Contact {
            get {
                return ResourceManager.GetString("L-Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_Language {
            get {
                return ResourceManager.GetString("L-Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_Legal {
            get {
                return ResourceManager.GetString("L-Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_Partners {
            get {
                return ResourceManager.GetString("L-Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_Privacy {
            get {
                return ResourceManager.GetString("L-Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string L_Product {
            get {
                return ResourceManager.GetString("L-Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string M_Text {
            get {
                return ResourceManager.GetString("M-Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string M_Title {
            get {
                return ResourceManager.GetString("M-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MA_Add {
            get {
                return ResourceManager.GetString("MA-Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MA_Cancel {
            get {
                return ResourceManager.GetString("MA-Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MA_Close {
            get {
                return ResourceManager.GetString("MA-Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MA_Edit {
            get {
                return ResourceManager.GetString("MA-Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MA_Name {
            get {
                return ResourceManager.GetString("MA-Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAB_Category {
            get {
                return ResourceManager.GetString("MAB-Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAB_CategorySelect {
            get {
                return ResourceManager.GetString("MAB-CategorySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAB_Document {
            get {
                return ResourceManager.GetString("MAB-Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAB_Title {
            get {
                return ResourceManager.GetString("MAB-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAD_Delete {
            get {
                return ResourceManager.GetString("MAD-Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAD_Text {
            get {
                return ResourceManager.GetString("MAD-Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAD_Title {
            get {
                return ResourceManager.GetString("MAD-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Desc {
            get {
                return ResourceManager.GetString("MAP-Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Description {
            get {
                return ResourceManager.GetString("MAP-Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Email {
            get {
                return ResourceManager.GetString("MAP-Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Firstname {
            get {
                return ResourceManager.GetString("MAP-Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Image {
            get {
                return ResourceManager.GetString("MAP-Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Lastname {
            get {
                return ResourceManager.GetString("MAP-Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Logo {
            get {
                return ResourceManager.GetString("MAP-Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Phone {
            get {
                return ResourceManager.GetString("MAP-Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Phone2 {
            get {
                return ResourceManager.GetString("MAP-Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Role {
            get {
                return ResourceManager.GetString("MAP-Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAP_Website {
            get {
                return ResourceManager.GetString("MAP-Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAPa_Title {
            get {
                return ResourceManager.GetString("MAPa-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAPe_Title {
            get {
                return ResourceManager.GetString("MAPe-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAPr_Title {
            get {
                return ResourceManager.GetString("MAPr-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEB_Title {
            get {
                return ResourceManager.GetString("MEB-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Add {
            get {
                return ResourceManager.GetString("MEI-Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_AddE {
            get {
                return ResourceManager.GetString("MEI-AddE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Description {
            get {
                return ResourceManager.GetString("MEI-Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Email {
            get {
                return ResourceManager.GetString("MEI-Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Emails {
            get {
                return ResourceManager.GetString("MEI-Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Infos {
            get {
                return ResourceManager.GetString("MEI-Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Name {
            get {
                return ResourceManager.GetString("MEI-Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Text {
            get {
                return ResourceManager.GetString("MEI-Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Title {
            get {
                return ResourceManager.GetString("MEI-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEI_Type {
            get {
                return ResourceManager.GetString("MEI-Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEPe_Title {
            get {
                return ResourceManager.GetString("MEPe-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MEPr_Title {
            get {
                return ResourceManager.GetString("MEPr-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string P_Title {
            get {
                return ResourceManager.GetString("P-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_Exist {
            get {
                return ResourceManager.GetString("Pa-Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_F20 {
            get {
                return ResourceManager.GetString("Pa-F20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_FPNG {
            get {
                return ResourceManager.GetString("Pa-FPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_Individuals {
            get {
                return ResourceManager.GetString("Pa-Individuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_IR {
            get {
                return ResourceManager.GetString("Pa-IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_N50 {
            get {
                return ResourceManager.GetString("Pa-N50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_NoPartners {
            get {
                return ResourceManager.GetString("Pa-NoPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_NR {
            get {
                return ResourceManager.GetString("Pa-NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_Proffesionnals {
            get {
                return ResourceManager.GetString("Pa-Proffesionnals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_Title {
            get {
                return ResourceManager.GetString("Pa-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_URL {
            get {
                return ResourceManager.GetString("Pa-URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_W250 {
            get {
                return ResourceManager.GetString("Pa-W250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pa_WR {
            get {
                return ResourceManager.GetString("Pa-WR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Po_Text {
            get {
                return ResourceManager.GetString("Po-Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Po_Title {
            get {
                return ResourceManager.GetString("Po-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_20P {
            get {
                return ResourceManager.GetString("Pr-20P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_50U {
            get {
                return ResourceManager.GetString("Pr-50U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_8P {
            get {
                return ResourceManager.GetString("Pr-8P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_AddProduct {
            get {
                return ResourceManager.GetString("Pr-AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_ChangeP {
            get {
                return ResourceManager.GetString("Pr-ChangeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_ChangeU {
            get {
                return ResourceManager.GetString("Pr-ChangeU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_ConfirmP {
            get {
                return ResourceManager.GetString("Pr-ConfirmP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_CurrentP {
            get {
                return ResourceManager.GetString("Pr-CurrentP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_CurrentU {
            get {
                return ResourceManager.GetString("Pr-CurrentU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_D20 {
            get {
                return ResourceManager.GetString("Pr-D20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_D200 {
            get {
                return ResourceManager.GetString("Pr-D200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_Exist {
            get {
                return ResourceManager.GetString("Pr-Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_Expression {
            get {
                return ResourceManager.GetString("Pr-Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_IncorrectP {
            get {
                return ResourceManager.GetString("Pr-IncorrectP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_IPNG {
            get {
                return ResourceManager.GetString("Pr-IPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_Logout {
            get {
                return ResourceManager.GetString("Pr-Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_MyP {
            get {
                return ResourceManager.GetString("Pr-MyP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_NewP {
            get {
                return ResourceManager.GetString("Pr-NewP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_NewU {
            get {
                return ResourceManager.GetString("Pr-NewU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_Nothing {
            get {
                return ResourceManager.GetString("Pr-Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_RequiredConfirmP {
            get {
                return ResourceManager.GetString("Pr-RequiredConfirmP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_RequiredNewP {
            get {
                return ResourceManager.GetString("Pr-RequiredNewP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_RequiredP {
            get {
                return ResourceManager.GetString("Pr-RequiredP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_RequiredU {
            get {
                return ResourceManager.GetString("Pr-RequiredU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_SuccessP {
            get {
                return ResourceManager.GetString("Pr-SuccessP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_SuccessU {
            get {
                return ResourceManager.GetString("Pr-SuccessU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_SwitchP {
            get {
                return ResourceManager.GetString("Pr-SwitchP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_SwitchUsername {
            get {
                return ResourceManager.GetString("Pr-SwitchUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_Title {
            get {
                return ResourceManager.GetString("Pr-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_TranslateB {
            get {
                return ResourceManager.GetString("Pr-TranslateB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Pr_WrongP {
            get {
                return ResourceManager.GetString("Pr-WrongP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string S_AddSolution {
            get {
                return ResourceManager.GetString("S-AddSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string S_Looking {
            get {
                return ResourceManager.GetString("S-Looking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string S_NoLooking {
            get {
                return ResourceManager.GetString("S-NoLooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string S_NoProducts {
            get {
                return ResourceManager.GetString("S-NoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string S_Title {
            get {
                return ResourceManager.GetString("S-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SD_Title {
            get {
                return ResourceManager.GetString("SD-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_Automatic {
            get {
                return ResourceManager.GetString("T-Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_Cancel {
            get {
                return ResourceManager.GetString("T-Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_Confirm {
            get {
                return ResourceManager.GetString("T-Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_ConfirmT {
            get {
                return ResourceManager.GetString("T-ConfirmT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_Nothing {
            get {
                return ResourceManager.GetString("T-Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_OriginalT {
            get {
                return ResourceManager.GetString("T-OriginalT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_Submit {
            get {
                return ResourceManager.GetString("T-Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_T200 {
            get {
                return ResourceManager.GetString("T-T200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_Title {
            get {
                return ResourceManager.GetString("T-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_TR {
            get {
                return ResourceManager.GetString("T-TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_Validation {
            get {
                return ResourceManager.GetString("T-Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string T_ValidationB {
            get {
                return ResourceManager.GetString("T-ValidationB", resourceCulture);
            }
        }
    }
}
